### ISSUE TITLE
Avoid concatenation of translated strings

### ISSUE THREAD

**Issue by louisroyer** [runsy/brewing#4]
[This](https://github.com/runsy/brewing/blob/a57480b80cf44cd4872ec289c7cdfc4017e10130/api.lua#L16) can lead to impossible translations: for example "Speed Potion" in french is "Potion de vitesse" (reversed order).

Consider replacing `name.." "..S("Potion")` with `S("@1 Potion", name)`. See [lua api](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3192) for more infos.

Also, some strings in [`locale/brewing.es.tr`](https://github.com/runsy/brewing/blob/master/locale/brewing.es.tr) seems not used anymore.

**Comment by runsy** [comment]
> [This](https://github.com/runsy/brewing/blob/a57480b80cf44cd4872ec289c7cdfc4017e10130/api.lua#L16) can lead to impossible translations: for example "Speed Potion" in french is "Potion de vitesse" (reversed order).
> 
> Consider replacing `name.." "..S("Potion")` with `S("@1 Potion", name)`. See [lua api](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3192) for more infos.

Yes, I changed! Thanks!

> 
> Also, some strings in [`locale/brewing.es.tr`](https://github.com/runsy/brewing/blob/master/locale/brewing.es.tr) seems not used anymore.

I do not think so. An example?

**Comment by louisroyer** [comment]
Ouair=Aire (un solo uso)
Ouhealth=Salud (un solo uso)
type=tipo

**Comment by louisroyer** [comment]
Maybe you could also replace [`S("You are under the effects of the").." "..type.." "..S("potion.")`](https://github.com/runsy/brewing/blob/master/effects.lua#L157) by `S("You are under the effects of the @1 potion.", type)` and [`S("The effects of the").." "..type.." "..S("potion have worn off.")`](https://github.com/runsy/brewing/blob/master/effects.lua#L161) by `S("The effects of the @1 potion have worn off.", type)`.
